import { createContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type AccentColor = "blue" | "cyan" | "indigo" | "emerald";
export type LanguageOption = "es" | "en" | "fr" | "pt";

interface ThemeContextValue {
  darkMode: boolean;
  setDarkMode: (value: boolean) => void;
  accentColor: AccentColor;
  setAccentColor: (value: AccentColor) => void;
  language: LanguageOption;
  setLanguage: (value: LanguageOption) => void;
  t: (key: string) => string;
}

export const ThemeContext = createContext<ThemeContextValue | null>(null);

const getStoredBoolean = (key: string) => localStorage.getItem(key) === "true";

const translations: Record<LanguageOption, Record<string, string>> = {
  es: {
    "nav.home": "Inicio",
    "nav.services": "Servicios",
    "nav.vehicles": "Vehículos",
    "nav.brands": "Marcas",
    "nav.map": "Mapa",
    "nav.operators": "Operadores",
    "nav.turns": "Turnos",
    "nav.settings": "Configuración",
    "common.all": "Todos",
    "common.activePlural": "Activos",
    "common.inactivePlural": "Inactivos",
    "common.loading": "Cargando...",
    "common.actions": "Acciones",
    "common.status": "Estado",
    "common.total": "Total",
    "common.client": "Cliente",
    "common.vehicle": "Vehículo",
    "common.service": "Servicio",
    "common.operator": "Operador",
    "common.time": "Hora",
    "common.price": "Precio",
    "common.duration": "Duración",
    "common.dateTime": "Fecha / hora",
    "common.noReservations": "No hay reservas para mostrar.",
    "common.name": "Nombre",
    "common.lastName": "Apellidos",
    "common.email": "Correo",
    "common.created": "Creado",
    "common.active": "Activo",
    "common.inactive": "Inactivo",
    "common.activate": "Activar",
    "common.deactivate": "Desactivar",
    "common.pending": "Pendiente",
    "common.assigned": "Asignada",
    "common.inProgress": "En proceso",
    "common.finished": "Finalizada",
    "common.cancelled": "Cancelada",
    "common.searchByName": "Buscar por nombre...",
    "common.noResults": "No se encontraron resultados.",
    "common.description": "Descripción",
    "common.edit": "Editar",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.backToSettings": "Volver a configuración",
    "settings.eyebrow": "Centro de configuración",
    "settings.title": "Configuración",
    "settings.subtitle": "Ajusta tu perfil, sesión y apariencia del panel administrativo.",
    "settings.profile.title": "Mi perfil",
    "settings.profile.desc": "Consulta y actualiza tus datos de administrador.",
    "settings.profile.action": "Abrir perfil",
    "settings.password.title": "Restablecer contraseña",
    "settings.password.desc": "Solicita un enlace para restablecer tu contraseña cuando lo necesites.",
    "settings.password.action": "Ir a restablecimiento",
    "settings.mode.title": "Modo de interfaz",
    "settings.mode.desc": "Cambia entre modo claro y modo oscuro en todo el panel.",
    "settings.mode.dark": "Modo oscuro",
    "settings.mode.light": "Modo claro",
    "settings.color.title": "Color de interfaz",
    "settings.color.desc": "Elige el acento visual principal para botones, enlaces y estados activos.",
    "settings.language.title": "Idioma",
    "settings.language.desc": "Cambia el idioma visible de la interfaz administrativa.",
    "settings.logout.title": "Cerrar sesión",
    "settings.logout.desc": "Finaliza tu acceso administrativo y vuelve a la pantalla principal.",
    "settings.logout.action": "Cerrar sesión",
    "logout.confirmTitle": "¿Deseas cerrar sesión?",
    "logout.confirmDesc": "Tu sesión actual finalizará. Deberás ingresar tus credenciales nuevamente para acceder al sistema.",
    "color.blue": "Azul",
    "color.cyan": "Celeste",
    "color.indigo": "Índigo",
    "color.emerald": "Verde",
    "language.es": "Español",
    "language.en": "Inglés",
    "language.fr": "Francés",
    "language.pt": "Portugués",
    "landing.brand": "Lava Rápido",
    "landing.features": "Funciones",
    "landing.operation": "Operación",
    "landing.security": "Seguridad",
    "landing.adminAccess": "Acceso administrativo",
    "landing.eyebrow": "Gestión rápida para tu lavadero",
    "landing.title": "Administra tu lavadero desde un solo lugar",
    "landing.description": "Agenda servicios, gestiona turnos, controla operadores, vehículos, marcas y pagos desde una plataforma administrativa clara y eficiente.",
    "landing.register": "Registrar usuario",
    "landing.resetPassword": "Restablecer contraseña",
    "landing.note": "Web exclusiva para administradores. Usuarios y operadores acceden desde la app móvil.",
    "landing.section.title": "Una operación más clara para cada servicio",
    "landing.band": "Reservas, catálogo, operadores, vehículos, marcas, ubicaciones y pagos.",
    "landing.feature.turns.title": "Turnos y reservas",
    "landing.feature.turns.desc": "Agenda servicios, consulta estados y controla la operación diaria.",
    "landing.feature.operators.title": "Operadores",
    "landing.feature.operators.desc": "Asigna personal activo y acompaña cada lavado hasta finalizarlo.",
    "landing.feature.payments.title": "Pagos Wompi",
    "landing.feature.payments.desc": "Gestiona cobros y verifica pagos desde el panel administrativo.",
    "landing.feature.vehicles.title": "Vehículos y marcas",
    "landing.feature.vehicles.desc": "Administra datos clave del cliente, placa, marca y estado.",
    "panel.eyebrow": "Administración general",
    "panel.title": "Panel principal",
    "panel.subtitle": "Resumen diario y rendimiento mensual del lavadero",
    "panel.inProgressToday": "En proceso hoy",
    "panel.pendingToday": "Pendientes hoy",
    "panel.finishedToday": "Finalizados hoy",
    "panel.totalToday": "Total del día",
    "panel.monthIncome": "Ingresos estimados del mes",
    "panel.monthIncomeNote": "Calculado con reservas finalizadas",
    "panel.monthReservations": "Reservas del mes",
    "panel.finished": "finalizadas",
    "panel.pendingAssigned": "Pendientes / asignadas",
    "panel.needsFollowUp": "Requieren seguimiento",
    "panel.cancelled": "Canceladas",
    "panel.operationalControl": "Control operativo",
    "panel.efficiency": "Efectividad",
    "panel.cancellation": "Cancelación",
    "panel.todayOperation": "Operación del día",
    "panel.todayOperationDesc": "Turnos activos, asignados y finalizados para hoy.",
    "panel.currentTurns": "Turnos en curso",
    "auth.loginTitle": "Acceso administrativo",
    "auth.loginSubtitle": "Ingresa con tu cuenta de administrador.",
    "auth.email": "Correo electrónico",
    "auth.password": "Contraseña",
    "auth.signingIn": "Iniciando sesión...",
    "auth.signIn": "Iniciar sesión",
    "auth.resetPasswordTitle": "Restablecer contraseña",
    "auth.resetPasswordSubtitle": "Ingresa tu correo y te enviaremos un enlace para crear una nueva contraseña.",
    "auth.sendReset": "Enviar enlace de restablecimiento",
    "auth.sending": "Enviando...",
    "auth.checkEmail": "Revisa tu correo",
    "auth.passwordUpdated": "Contraseña actualizada",
    "auth.newPassword": "Nueva contraseña",
    "auth.newPasswordSubtitle": "Ingresa y confirma tu nueva contraseña.",
    "auth.confirmPassword": "Confirmar contraseña",
    "auth.updatePassword": "Actualizar contraseña",
    "auth.updating": "Actualizando...",
    "profile.title": "Mi perfil",
    "profile.subtitle": "Consulta y actualiza la información de tu cuenta de administrador.",
    "profile.role": "Administrador",
    "profile.save": "Guardar cambios",
    "profile.saving": "Guardando...",
    "services.title": "Servicios",
    "services.new": "Nuevo servicio",
    "services.loading": "Cargando servicios...",
    "services.edit": "Editar servicio",
    "services.name": "Nombre",
    "vehicles.title": "Vehículos",
    "vehicles.subtitle": "Gestión de vehículos, propietarios y estado operativo.",
    "vehicles.search": "Buscar por placa, marca, propietario o email...",
    "vehicles.loading": "Cargando vehículos...",
    "vehicles.empty": "No hay vehículos para mostrar.",
    "brands.title": "Marcas",
    "brands.subtitle": "Administración de marcas asociadas a los vehículos.",
    "brands.loading": "Cargando marcas...",
    "brands.empty": "No hay marcas para mostrar.",
    "operators.title": "Operadores",
    "operators.subtitle": "Gestión del personal de lavado",
    "operators.new": "Nuevo operador",
    "operators.assign": "Asignar operador",
    "operators.assigning": "Asignando...",
    "operators.modalSubtitle": "Asigna rol de operador a un usuario existente",
    "operators.disableAll": "Desactivar todos",
    "operators.loading": "Cargando operadores...",
    "operators.empty": "No hay operadores registrados.",
    "turns.title": "Turnos",
    "turns.subtitle": "Supervisa y gestiona las reservas del lava rápido.",
    "turns.newWalkIn": "Registrar reserva presencial",
    "turns.active": "Activos",
    "turns.pendingPlural": "Pendientes",
    "turns.assignedPlural": "Asignadas",
    "turns.inProgress": "En proceso",
    "turns.finishedPlural": "Finalizadas",
    "turns.cancelledPlural": "Canceladas",
    "turns.search": "Buscar por cliente o placa...",
    "turns.payment": "Pago",
    "turns.view": "Ver",
    "map.title": "Ubicaciones",
    "map.subtitle": "Puntos de atención registrados",
    "map.panel": "Autolavados",
  },
  en: {
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.vehicles": "Vehicles",
    "nav.brands": "Brands",
    "nav.map": "Map",
    "nav.operators": "Operators",
    "nav.turns": "Appointments",
    "nav.settings": "Settings",
    "common.all": "All",
    "common.activePlural": "Active",
    "common.inactivePlural": "Inactive",
    "common.loading": "Loading...",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.total": "Total",
    "common.client": "Client",
    "common.vehicle": "Vehicle",
    "common.service": "Service",
    "common.operator": "Operator",
    "common.time": "Time",
    "common.price": "Price",
    "common.duration": "Duration",
    "common.dateTime": "Date / time",
    "common.noReservations": "No appointments to show.",
    "common.name": "Name",
    "common.lastName": "Last name",
    "common.email": "Email",
    "common.created": "Created",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.activate": "Activate",
    "common.deactivate": "Deactivate",
    "common.pending": "Pending",
    "common.assigned": "Assigned",
    "common.inProgress": "In progress",
    "common.finished": "Finished",
    "common.cancelled": "Cancelled",
    "common.searchByName": "Search by name...",
    "common.noResults": "No results found.",
    "common.description": "Description",
    "common.edit": "Edit",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.backToSettings": "Back to settings",
    "settings.eyebrow": "Settings center",
    "settings.title": "Settings",
    "settings.subtitle": "Adjust your profile, session and admin panel appearance.",
    "settings.profile.title": "My profile",
    "settings.profile.desc": "View and update your administrator details.",
    "settings.profile.action": "Open profile",
    "settings.password.title": "Reset password",
    "settings.password.desc": "Request a link to reset your password when needed.",
    "settings.password.action": "Go to reset",
    "settings.mode.title": "Interface mode",
    "settings.mode.desc": "Switch between light and dark mode across the panel.",
    "settings.mode.dark": "Dark mode",
    "settings.mode.light": "Light mode",
    "settings.color.title": "Interface color",
    "settings.color.desc": "Choose the main accent for buttons, links and active states.",
    "settings.language.title": "Language",
    "settings.language.desc": "Change the visible language of the admin interface.",
    "settings.logout.title": "Sign out",
    "settings.logout.desc": "End your admin session and return to the main screen.",
    "settings.logout.action": "Sign out",
    "logout.confirmTitle": "Do you want to sign out?",
    "logout.confirmDesc": "Your current session will end. You will need to enter your credentials again to access the system.",
    "color.blue": "Blue",
    "color.cyan": "Cyan",
    "color.indigo": "Indigo",
    "color.emerald": "Green",
    "language.es": "Spanish",
    "language.en": "English",
    "language.fr": "French",
    "language.pt": "Portuguese",
    "landing.brand": "Lava Rápido",
    "landing.features": "Features",
    "landing.operation": "Operation",
    "landing.security": "Security",
    "landing.adminAccess": "Admin access",
    "landing.eyebrow": "Fast management for your car wash",
    "landing.title": "Manage your car wash from one place",
    "landing.description": "Schedule services, manage appointments, control operators, vehicles, brands and payments from a clear and efficient admin platform.",
    "landing.register": "Register user",
    "landing.resetPassword": "Reset password",
    "landing.note": "Admin-only web. Users and operators access from the mobile app.",
    "landing.section.title": "A clearer operation for every service",
    "landing.band": "Appointments, catalog, operators, vehicles, brands, locations and payments.",
    "landing.feature.turns.title": "Appointments",
    "landing.feature.turns.desc": "Schedule services, check statuses and control daily operations.",
    "landing.feature.operators.title": "Operators",
    "landing.feature.operators.desc": "Assign active staff and follow every wash until completion.",
    "landing.feature.payments.title": "Wompi payments",
    "landing.feature.payments.desc": "Manage charges and verify payments from the admin panel.",
    "landing.feature.vehicles.title": "Vehicles and brands",
    "landing.feature.vehicles.desc": "Manage key customer, plate, brand and status details.",
    "panel.eyebrow": "General administration",
    "panel.title": "Main dashboard",
    "panel.subtitle": "Daily summary and monthly car wash performance",
    "panel.inProgressToday": "In progress today",
    "panel.pendingToday": "Pending today",
    "panel.finishedToday": "Finished today",
    "panel.totalToday": "Today's total",
    "panel.monthIncome": "Estimated monthly income",
    "panel.monthIncomeNote": "Calculated from finished appointments",
    "panel.monthReservations": "Monthly appointments",
    "panel.finished": "finished",
    "panel.pendingAssigned": "Pending / assigned",
    "panel.needsFollowUp": "Needs follow-up",
    "panel.cancelled": "Cancelled",
    "panel.operationalControl": "Operational control",
    "panel.efficiency": "Efficiency",
    "panel.cancellation": "Cancellation",
    "panel.todayOperation": "Today's operation",
    "panel.todayOperationDesc": "Active, assigned and finished appointments for today.",
    "panel.currentTurns": "Current appointments",
    "auth.loginTitle": "Admin access",
    "auth.loginSubtitle": "Sign in with your administrator account.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signingIn": "Signing in...",
    "auth.signIn": "Sign in",
    "auth.resetPasswordTitle": "Reset password",
    "auth.resetPasswordSubtitle": "Enter your email and we will send you a link to create a new password.",
    "auth.sendReset": "Send reset link",
    "auth.sending": "Sending...",
    "auth.checkEmail": "Check your email",
    "auth.passwordUpdated": "Password updated",
    "auth.newPassword": "New password",
    "auth.newPasswordSubtitle": "Enter and confirm your new password.",
    "auth.confirmPassword": "Confirm password",
    "auth.updatePassword": "Update password",
    "auth.updating": "Updating...",
    "profile.title": "My profile",
    "profile.subtitle": "View and update your administrator account information.",
    "profile.role": "Administrator",
    "profile.save": "Save changes",
    "profile.saving": "Saving...",
    "services.title": "Services",
    "services.new": "New service",
    "services.loading": "Loading services...",
    "services.edit": "Edit service",
    "services.name": "Name",
    "vehicles.title": "Vehicles",
    "vehicles.subtitle": "Manage vehicles, owners and operational status.",
    "vehicles.search": "Search by plate, brand, owner or email...",
    "vehicles.loading": "Loading vehicles...",
    "vehicles.empty": "No vehicles to show.",
    "brands.title": "Brands",
    "brands.subtitle": "Manage brands associated with vehicles.",
    "brands.loading": "Loading brands...",
    "brands.empty": "No brands to show.",
    "operators.title": "Operators",
    "operators.subtitle": "Manage washing staff",
    "operators.new": "New operator",
    "operators.assign": "Assign operator",
    "operators.assigning": "Assigning...",
    "operators.modalSubtitle": "Assign the operator role to an existing user",
    "operators.disableAll": "Disable all",
    "operators.loading": "Loading operators...",
    "operators.empty": "No operators registered.",
    "turns.title": "Appointments",
    "turns.subtitle": "Monitor and manage car wash appointments.",
    "turns.newWalkIn": "Register walk-in appointment",
    "turns.active": "Active",
    "turns.pendingPlural": "Pending",
    "turns.assignedPlural": "Assigned",
    "turns.inProgress": "In progress",
    "turns.finishedPlural": "Finished",
    "turns.cancelledPlural": "Cancelled",
    "turns.search": "Search by client or plate...",
    "turns.payment": "Payment",
    "turns.view": "View",
    "map.title": "Locations",
    "map.subtitle": "Registered service points",
    "map.panel": "Car washes",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.services": "Services",
    "nav.vehicles": "Véhicules",
    "nav.brands": "Marques",
    "nav.map": "Carte",
    "nav.operators": "Opérateurs",
    "nav.turns": "Réservations",
    "nav.settings": "Paramètres",
    "common.all": "Tous",
    "common.activePlural": "Actifs",
    "common.inactivePlural": "Inactifs",
    "common.loading": "Chargement...",
    "common.actions": "Actions",
    "common.status": "État",
    "common.total": "Total",
    "common.client": "Client",
    "common.vehicle": "Véhicule",
    "common.service": "Service",
    "common.operator": "Opérateur",
    "common.time": "Heure",
    "common.price": "Prix",
    "common.duration": "Durée",
    "common.dateTime": "Date / heure",
    "common.noReservations": "Aucune réservation à afficher.",
    "common.name": "Nom",
    "common.lastName": "Nom de famille",
    "common.email": "E-mail",
    "common.created": "Créé",
    "common.active": "Actif",
    "common.inactive": "Inactif",
    "common.activate": "Activer",
    "common.deactivate": "Désactiver",
    "common.pending": "En attente",
    "common.assigned": "Assignée",
    "common.inProgress": "En cours",
    "common.finished": "Terminée",
    "common.cancelled": "Annulée",
    "common.searchByName": "Rechercher par nom...",
    "common.noResults": "Aucun résultat trouvé.",
    "common.description": "Description",
    "common.edit": "Modifier",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.backToSettings": "Retour aux paramètres",
    "settings.eyebrow": "Centre de paramètres",
    "settings.title": "Paramètres",
    "settings.subtitle": "Ajustez votre profil, votre session et l'apparence du panneau.",
    "settings.profile.title": "Mon profil",
    "settings.profile.desc": "Consultez et mettez à jour vos données administrateur.",
    "settings.profile.action": "Ouvrir le profil",
    "settings.password.title": "Réinitialiser le mot de passe",
    "settings.password.desc": "Demandez un lien pour réinitialiser votre mot de passe.",
    "settings.password.action": "Aller à la réinitialisation",
    "settings.mode.title": "Mode d'interface",
    "settings.mode.desc": "Passez du mode clair au mode sombre dans tout le panneau.",
    "settings.mode.dark": "Mode sombre",
    "settings.mode.light": "Mode clair",
    "settings.color.title": "Couleur d'interface",
    "settings.color.desc": "Choisissez l'accent principal pour boutons, liens et états actifs.",
    "settings.language.title": "Langue",
    "settings.language.desc": "Changez la langue visible de l'interface administrative.",
    "settings.logout.title": "Fermer la session",
    "settings.logout.desc": "Terminez votre accès administrateur et revenez à l'écran principal.",
    "settings.logout.action": "Fermer la session",
    "logout.confirmTitle": "Voulez-vous fermer la session ?",
    "logout.confirmDesc": "Votre session actuelle se terminera. Vous devrez saisir à nouveau vos identifiants.",
    "color.blue": "Bleu",
    "color.cyan": "Céleste",
    "color.indigo": "Indigo",
    "color.emerald": "Vert",
    "language.es": "Espagnol",
    "language.en": "Anglais",
    "language.fr": "Français",
    "language.pt": "Portugais",
    "landing.brand": "Lava Rápido",
    "landing.features": "Fonctions",
    "landing.operation": "Opération",
    "landing.security": "Sécurité",
    "landing.adminAccess": "Accès administrateur",
    "landing.eyebrow": "Gestion rapide pour votre lavage auto",
    "landing.title": "Gérez votre lavage auto depuis un seul endroit",
    "landing.description": "Planifiez les services, gérez les réservations, contrôlez les opérateurs, véhicules, marques et paiements depuis une plateforme claire.",
    "landing.register": "Inscrire un utilisateur",
    "landing.resetPassword": "Réinitialiser le mot de passe",
    "landing.note": "Web réservée aux administrateurs. Utilisateurs et opérateurs accèdent depuis l'app mobile.",
    "landing.section.title": "Une opération plus claire pour chaque service",
    "landing.band": "Réservations, catalogue, opérateurs, véhicules, marques, emplacements et paiements.",
    "landing.feature.turns.title": "Réservations",
    "landing.feature.turns.desc": "Planifiez les services, consultez les états et contrôlez l'opération quotidienne.",
    "landing.feature.operators.title": "Opérateurs",
    "landing.feature.operators.desc": "Assignez le personnel actif et suivez chaque lavage jusqu'à la fin.",
    "landing.feature.payments.title": "Paiements Wompi",
    "landing.feature.payments.desc": "Gérez les paiements et vérifiez-les depuis le panneau administrateur.",
    "landing.feature.vehicles.title": "Véhicules et marques",
    "landing.feature.vehicles.desc": "Administrez les données client, plaque, marque et état.",
    "panel.eyebrow": "Administration générale",
    "panel.title": "Panneau principal",
    "panel.subtitle": "Résumé quotidien et performance mensuelle du lavage auto",
    "panel.inProgressToday": "En cours aujourd'hui",
    "panel.pendingToday": "En attente aujourd'hui",
    "panel.finishedToday": "Terminés aujourd'hui",
    "panel.totalToday": "Total du jour",
    "panel.monthIncome": "Revenus mensuels estimés",
    "panel.monthIncomeNote": "Calculé avec les réservations terminées",
    "panel.monthReservations": "Réservations du mois",
    "panel.finished": "terminées",
    "panel.pendingAssigned": "En attente / assignées",
    "panel.needsFollowUp": "Nécessitent un suivi",
    "panel.cancelled": "Annulées",
    "panel.operationalControl": "Contrôle opérationnel",
    "panel.efficiency": "Efficacité",
    "panel.cancellation": "Annulation",
    "panel.todayOperation": "Opération du jour",
    "panel.todayOperationDesc": "Réservations actives, assignées et terminées aujourd'hui.",
    "panel.currentTurns": "Réservations en cours",
    "auth.loginTitle": "Accès administrateur",
    "auth.loginSubtitle": "Connectez-vous avec votre compte administrateur.",
    "auth.email": "E-mail",
    "auth.password": "Mot de passe",
    "auth.signingIn": "Connexion...",
    "auth.signIn": "Se connecter",
    "auth.resetPasswordTitle": "Réinitialiser le mot de passe",
    "auth.resetPasswordSubtitle": "Entrez votre e-mail et nous vous enverrons un lien.",
    "auth.sendReset": "Envoyer le lien",
    "auth.sending": "Envoi...",
    "auth.checkEmail": "Vérifiez votre e-mail",
    "auth.passwordUpdated": "Mot de passe mis à jour",
    "auth.newPassword": "Nouveau mot de passe",
    "auth.newPasswordSubtitle": "Entrez et confirmez votre nouveau mot de passe.",
    "auth.confirmPassword": "Confirmer le mot de passe",
    "auth.updatePassword": "Mettre à jour",
    "auth.updating": "Mise à jour...",
    "profile.title": "Mon profil",
    "profile.subtitle": "Consultez et mettez à jour votre compte administrateur.",
    "profile.role": "Administrateur",
    "profile.save": "Enregistrer",
    "profile.saving": "Enregistrement...",
    "services.title": "Services",
    "services.new": "Nouveau service",
    "services.loading": "Chargement des services...",
    "services.edit": "Modifier le service",
    "services.name": "Nom",
    "vehicles.title": "Véhicules",
    "vehicles.subtitle": "Gestion des véhicules, propriétaires et état opérationnel.",
    "vehicles.search": "Rechercher par plaque, marque, propriétaire ou e-mail...",
    "vehicles.loading": "Chargement des véhicules...",
    "vehicles.empty": "Aucun véhicule à afficher.",
    "brands.title": "Marques",
    "brands.subtitle": "Administration des marques associées aux véhicules.",
    "brands.loading": "Chargement des marques...",
    "brands.empty": "Aucune marque à afficher.",
    "operators.title": "Opérateurs",
    "operators.subtitle": "Gestion du personnel de lavage",
    "operators.new": "Nouvel opérateur",
    "operators.assign": "Assigner l'opérateur",
    "operators.assigning": "Assignation...",
    "operators.modalSubtitle": "Assignez le rôle d'opérateur à un utilisateur existant",
    "operators.disableAll": "Désactiver tous",
    "operators.loading": "Chargement des opérateurs...",
    "operators.empty": "Aucun opérateur enregistré.",
    "turns.title": "Réservations",
    "turns.subtitle": "Supervisez et gérez les réservations du lavage auto.",
    "turns.newWalkIn": "Enregistrer une réservation sur place",
    "turns.active": "Actives",
    "turns.pendingPlural": "En attente",
    "turns.assignedPlural": "Assignées",
    "turns.inProgress": "En cours",
    "turns.finishedPlural": "Terminées",
    "turns.cancelledPlural": "Annulées",
    "turns.search": "Rechercher par client ou plaque...",
    "turns.payment": "Paiement",
    "turns.view": "Voir",
    "map.title": "Emplacements",
    "map.subtitle": "Points de service enregistrés",
    "map.panel": "Lavages auto",
  },
  pt: {
    "nav.home": "Início",
    "nav.services": "Serviços",
    "nav.vehicles": "Veículos",
    "nav.brands": "Marcas",
    "nav.map": "Mapa",
    "nav.operators": "Operadores",
    "nav.turns": "Agendamentos",
    "nav.settings": "Configuração",
    "common.all": "Todos",
    "common.activePlural": "Ativos",
    "common.inactivePlural": "Inativos",
    "common.loading": "Carregando...",
    "common.actions": "Ações",
    "common.status": "Estado",
    "common.total": "Total",
    "common.client": "Cliente",
    "common.vehicle": "Veículo",
    "common.service": "Serviço",
    "common.operator": "Operador",
    "common.time": "Hora",
    "common.price": "Preço",
    "common.duration": "Duração",
    "common.dateTime": "Data / hora",
    "common.noReservations": "Não há reservas para mostrar.",
    "common.name": "Nome",
    "common.lastName": "Sobrenomes",
    "common.email": "E-mail",
    "common.created": "Criado",
    "common.active": "Ativo",
    "common.inactive": "Inativo",
    "common.activate": "Ativar",
    "common.deactivate": "Desativar",
    "common.pending": "Pendente",
    "common.assigned": "Atribuída",
    "common.inProgress": "Em processo",
    "common.finished": "Finalizada",
    "common.cancelled": "Cancelada",
    "common.searchByName": "Buscar por nome...",
    "common.noResults": "Nenhum resultado encontrado.",
    "common.description": "Descrição",
    "common.edit": "Editar",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.backToSettings": "Voltar à configuração",
    "settings.eyebrow": "Centro de configuração",
    "settings.title": "Configuração",
    "settings.subtitle": "Ajuste seu perfil, sessão e aparência do painel administrativo.",
    "settings.profile.title": "Meu perfil",
    "settings.profile.desc": "Consulte e atualize seus dados de administrador.",
    "settings.profile.action": "Abrir perfil",
    "settings.password.title": "Redefinir senha",
    "settings.password.desc": "Solicite um link para redefinir sua senha quando precisar.",
    "settings.password.action": "Ir para redefinição",
    "settings.mode.title": "Modo de interface",
    "settings.mode.desc": "Alterne entre modo claro e escuro em todo o painel.",
    "settings.mode.dark": "Modo escuro",
    "settings.mode.light": "Modo claro",
    "settings.color.title": "Cor da interface",
    "settings.color.desc": "Escolha o destaque principal para botões, links e estados ativos.",
    "settings.language.title": "Idioma",
    "settings.language.desc": "Altere o idioma visível da interface administrativa.",
    "settings.logout.title": "Encerrar sessão",
    "settings.logout.desc": "Finalize seu acesso administrativo e volte à tela principal.",
    "settings.logout.action": "Encerrar sessão",
    "logout.confirmTitle": "Deseja encerrar a sessão?",
    "logout.confirmDesc": "Sua sessão atual será encerrada. Você deverá inserir suas credenciais novamente para acessar o sistema.",
    "color.blue": "Azul",
    "color.cyan": "Celeste",
    "color.indigo": "Índigo",
    "color.emerald": "Verde",
    "language.es": "Espanhol",
    "language.en": "Inglês",
    "language.fr": "Francês",
    "language.pt": "Português",
    "landing.brand": "Lava Rápido",
    "landing.features": "Funções",
    "landing.operation": "Operação",
    "landing.security": "Segurança",
    "landing.adminAccess": "Acesso administrativo",
    "landing.eyebrow": "Gestão rápida para seu lava-rápido",
    "landing.title": "Gerencie seu lava-rápido em um só lugar",
    "landing.description": "Agende serviços, gerencie turnos, controle operadores, veículos, marcas e pagamentos em uma plataforma administrativa clara.",
    "landing.register": "Registrar usuário",
    "landing.resetPassword": "Redefinir senha",
    "landing.note": "Web exclusiva para administradores. Usuários e operadores acessam pelo app móvel.",
    "landing.section.title": "Uma operação mais clara para cada serviço",
    "landing.band": "Agendamentos, catálogo, operadores, veículos, marcas, localizações e pagamentos.",
    "landing.feature.turns.title": "Agendamentos",
    "landing.feature.turns.desc": "Agende serviços, consulte estados e controle a operação diária.",
    "landing.feature.operators.title": "Operadores",
    "landing.feature.operators.desc": "Atribua equipe ativa e acompanhe cada lavagem até finalizar.",
    "landing.feature.payments.title": "Pagamentos Wompi",
    "landing.feature.payments.desc": "Gerencie cobranças e verifique pagamentos no painel administrativo.",
    "landing.feature.vehicles.title": "Veículos e marcas",
    "landing.feature.vehicles.desc": "Administre dados de cliente, placa, marca e estado.",
    "panel.eyebrow": "Administração geral",
    "panel.title": "Painel principal",
    "panel.subtitle": "Resumo diário e desempenho mensal do lava-rápido",
    "panel.inProgressToday": "Em processo hoje",
    "panel.pendingToday": "Pendentes hoje",
    "panel.finishedToday": "Finalizados hoje",
    "panel.totalToday": "Total do dia",
    "panel.monthIncome": "Receita mensal estimada",
    "panel.monthIncomeNote": "Calculado com reservas finalizadas",
    "panel.monthReservations": "Reservas do mês",
    "panel.finished": "finalizadas",
    "panel.pendingAssigned": "Pendentes / atribuídas",
    "panel.needsFollowUp": "Precisam de acompanhamento",
    "panel.cancelled": "Canceladas",
    "panel.operationalControl": "Controle operacional",
    "panel.efficiency": "Eficiência",
    "panel.cancellation": "Cancelamento",
    "panel.todayOperation": "Operação do dia",
    "panel.todayOperationDesc": "Turnos ativos, atribuídos e finalizados para hoje.",
    "panel.currentTurns": "Turnos em curso",
    "auth.loginTitle": "Acesso administrativo",
    "auth.loginSubtitle": "Entre com sua conta de administrador.",
    "auth.email": "E-mail",
    "auth.password": "Senha",
    "auth.signingIn": "Entrando...",
    "auth.signIn": "Entrar",
    "auth.resetPasswordTitle": "Redefinir senha",
    "auth.resetPasswordSubtitle": "Digite seu e-mail e enviaremos um link para criar uma nova senha.",
    "auth.sendReset": "Enviar link",
    "auth.sending": "Enviando...",
    "auth.checkEmail": "Verifique seu e-mail",
    "auth.passwordUpdated": "Senha atualizada",
    "auth.newPassword": "Nova senha",
    "auth.newPasswordSubtitle": "Digite e confirme sua nova senha.",
    "auth.confirmPassword": "Confirmar senha",
    "auth.updatePassword": "Atualizar senha",
    "auth.updating": "Atualizando...",
    "profile.title": "Meu perfil",
    "profile.subtitle": "Consulte e atualize sua conta de administrador.",
    "profile.role": "Administrador",
    "profile.save": "Salvar alterações",
    "profile.saving": "Salvando...",
    "services.title": "Serviços",
    "services.new": "Novo serviço",
    "services.loading": "Carregando serviços...",
    "services.edit": "Editar serviço",
    "services.name": "Nome",
    "vehicles.title": "Veículos",
    "vehicles.subtitle": "Gestão de veículos, proprietários e estado operacional.",
    "vehicles.search": "Buscar por placa, marca, proprietário ou e-mail...",
    "vehicles.loading": "Carregando veículos...",
    "vehicles.empty": "Não há veículos para mostrar.",
    "brands.title": "Marcas",
    "brands.subtitle": "Administração de marcas associadas aos veículos.",
    "brands.loading": "Carregando marcas...",
    "brands.empty": "Não há marcas para mostrar.",
    "operators.title": "Operadores",
    "operators.subtitle": "Gestão da equipe de lavagem",
    "operators.new": "Novo operador",
    "operators.assign": "Atribuir operador",
    "operators.assigning": "Atribuindo...",
    "operators.modalSubtitle": "Atribua o papel de operador a um usuário existente",
    "operators.disableAll": "Desativar todos",
    "operators.loading": "Carregando operadores...",
    "operators.empty": "Não há operadores registrados.",
    "turns.title": "Turnos",
    "turns.subtitle": "Supervise e gerencie as reservas do lava-rápido.",
    "turns.newWalkIn": "Registrar reserva presencial",
    "turns.active": "Ativos",
    "turns.pendingPlural": "Pendentes",
    "turns.assignedPlural": "Atribuídas",
    "turns.inProgress": "Em processo",
    "turns.finishedPlural": "Finalizadas",
    "turns.cancelledPlural": "Canceladas",
    "turns.search": "Buscar por cliente ou placa...",
    "turns.payment": "Pagamento",
    "turns.view": "Ver",
    "map.title": "Localizações",
    "map.subtitle": "Pontos de atendimento registrados",
    "map.panel": "Lava-rápidos",
  },
};

export function ThemeProvider({ children }: { children: ReactNode }) {
  const [darkMode, setDarkMode] = useState(() => getStoredBoolean("lava-dark-mode"));
  const [accentColor, setAccentColor] = useState<AccentColor>(() => {
    const stored = localStorage.getItem("lava-accent-color");
    return stored === "cyan" || stored === "indigo" || stored === "emerald" ? stored : "blue";
  });
  const [language, setLanguage] = useState<LanguageOption>(() => {
    const stored = localStorage.getItem("lava-language");
    return stored === "en" || stored === "fr" || stored === "pt" ? stored : "es";
  });

  useEffect(() => {
    document.documentElement.dataset.theme = darkMode ? "dark" : "light";
    localStorage.setItem("lava-dark-mode", String(darkMode));
  }, [darkMode]);

  useEffect(() => {
    document.documentElement.dataset.accent = accentColor;
    localStorage.setItem("lava-accent-color", accentColor);
  }, [accentColor]);

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem("lava-language", language);
  }, [language]);

  const value = useMemo(
    () => ({
      darkMode,
      setDarkMode,
      accentColor,
      setAccentColor,
      language,
      setLanguage,
      t: (key: string) => translations[language][key] || translations.es[key] || key,
    }),
    [accentColor, darkMode, language]
  );

  return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>;
}
